import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { defineConfig, type Plugin } from 'vitest/config';

/**
 * Offline support: after the build, write sw.js listing every file of the app. The first visit
 * downloads them all (the geometry engine is the big one); after that CADDY opens with no internet.
 */
function offline(): Plugin {
  let outDir = 'dist';
  return {
    name: 'caddy-offline',
    apply: 'build',
    configResolved(c) { outDir = c.build.outDir; },
    closeBundle() {
      const files: string[] = [];
      const walk = (d: string): void => readdirSync(d).forEach((n) => { const p = join(d, n); if (statSync(p).isDirectory()) walk(p); else files.push(relative(outDir, p).split(sep).join('/')); });
      walk(outDir);
      const list = files.filter((f) => f !== 'sw.js').sort();
      const h = createHash('sha1');
      list.forEach((f) => { h.update(f); h.update(readFileSync(join(outDir, f))); });
      const sw = `// Generated by the build. Keeps CADDY available offline.
const CACHE = 'caddy-${h.digest('hex').slice(0, 12)}';
const FILES = ${JSON.stringify(['', ...list])};
const root = self.registration.scope;
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES.map((f) => new URL(f, root).href))));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith('caddy-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request, url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== location.origin) return;
  e.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || (req.mode === 'navigate' ? caches.match(new URL('index.html', root).href) : null) || fetch(req)));
});
`;
      writeFileSync(join(outDir, 'sw.js'), sw);
    },
  };
}

export default defineConfig({
  base: './',
  plugins: [offline()],
  worker: { format: 'es' },
  optimizeDeps: { exclude: ['replicad-opencascadejs'] },
  build: { target: 'es2022', chunkSizeWarningLimit: 2000 },
  test: {
    environment: 'node',
    include: ['tests/**/*.test.ts'],
    testTimeout: 60_000,
    hookTimeout: 120_000,
  },
});
